name: release pipeline
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: docker:stable
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u bsdlp -p $GITHUB_TOKEN
          docker pull docker.pkg.github.com/bsdlp/sab-notify-discord/sab-notify-discord:$GITHUB_SHA
          docker tag docker.pkg.github.com/bsdlp/sab-notify-discord/sab-notify-discord:$GITHUB_SHA docker.pkg.github.com/bsdlp/sab-notify-discord/sab-notify-discord:latest
          docker push docker.pkg.github.com/bsdlp/sab-notify-discord/sab-notify-discord:latest
