name: build pipeline
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint
    steps:
      - uses: actions/checkout@master
      - run: |
          golangci-lint run ./...

  test:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - uses: actions/checkout@master
      - run: |
          go test -v -race ./...

  build:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - uses: actions/checkout@master
      - run: go build ./...
